server:
  port: 8989
  servlet:
    context-path: /git_test
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:com/baizhi/dao/*Mapper.xml
spring:
  datasource:
    username: root
    password: ROOT
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    port: 7000
    database: 0
    host: 192.168.198.30